GET http://localhost:8080

###

GET http://localhost:8080/deal

###

http://localhost:8080/deal/0dd95d33-e4c4-4064-baf2-b9897917f49c

###

POST http://localhost:8080/deal
Content-Type: application/json

{"name": "TestTrans1", "type": "food","price": 22}

###

