GET http://localhost:8080

###

GET http://localhost:8080/deal

###

GET http://localhost:8080/deal/0dd95d33-e4c4-4064-baf2-b9897917f49c

###

POST http://localhost:8080/deal
Content-Type: application/json

{"name": "TestTrans2", "type": "food", "price": 22.00, "date": "2021-01-24T15:53:16"}

###

