GET http://localhost:8080/api/v1/item

###

POST http://localhost:8080/api/v1/deal/0aa458b5-8807-4bd4-a04a-26d4e96c050e/item
Content-Type: application/json

{"name": "Thing", "price": 11.00}

###

DELETE http://localhost:8080/api/v1/deal/123aaa45/item/606c6cb2-e609-4154-b081-79e16745728f

###