name: Java CI with Gradle

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

# The GitHub documentation says Ensure no Gradle daemons are running anymore when your workflow completes.
# Creating the cache package might fail due to locks being held by Gradle.
# For this reason, it’s a good idea to run your build with the --no-daemon flag
      - name: Build with Gradle
        run: ./gradlew finance-service:build --no-daemon
